### ISSUE TITLE
Unable to install package using composer

### ISSUE THREAD

**Issue by michielfb** [buckaroo-it/Magento#2]
Since version 5.2.1 it is no longer possible to install the extension using composer. After running `composer require buckaroo/magento1` the following error occurs.

```
Installation failed, reverting ./composer.json to its original content.

                                                                                   
  [ErrorException]                                                                 
  Unable to find deploy strategy for module: "buckaroo/magento1" no known mapping  
  sourceDir: "/data/magento/vendor/buckaroo/magento1" 
```

I believe this is because the `modman` file has been deleted. Can you re-introduce a way to install the extension using composer without manually copying files like explained in the composer install guide?

**Comment by vladislav-padalka-hys** [comment]
Hi Michiel !

Thanks for the report ! 
modman file has been restored in v5.2.2 
please check and let us know if it works for you!

**Comment by michielfb** [comment]
Hi @vladislav-padalka-hys, thanks for the update. I'm able to correctly install the extension now.
