### ISSUE TITLE
Updating to 1.16.1 doesn't take configuration changes for Default B2b Payment methods into account.

### ISSUE THREAD

**Issue by igorwulff** [buckaroo-it/Magento#4]
Hi Buckaroo,

Just wanted to report, after upgrading to 1.16.1 the old TIG buckaroo payment methods weren't transformed to the correct options in the B2B Magento 2 module. These configurations are located under B2B Features -> B2B Features -> Default B2B Payment Methods -> Payment Methods.

**Comment by Buckaroo-Rens** [comment]
@igorwulff  You posted the issue in Magento 1 repo, but all the information is M2 related. Can you confirm this is for Magento 2? Can you also give us any additional information about the old version you were running and they way you updated.

**Comment by Buckaroo-Rens** [comment]
@igorwulff  Can you provide any extra information?
